// <auto-generated />
namespace MapsProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addstatusrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addstatusrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201801191320077_Add status (required)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
